### PR TITLE
Document filesystem utils

### PR DESCRIPTION
**Pull request by appgurueu**
Still had this sitting on my harddrive mostly finished and didn't want it to go to waste.

### CODE REVIEW

**Review by wsor4035 — COMMENTED** [review]
isnt dir_delim depreciated now? might be worth documenting

**Comment by wsor4035** [comment]
not depreciated/removed yet, see https://github.com/minetest/minetest/pull/13759 - maybe worth noting that its not needed, etc or something

**Comment by appgurueu** [comment]
> not depreciated/removed yet, see [minetest/minetest#13759](https://github.com/minetest/minetest/pull/13759) - maybe worth noting that its not needed, etc or something

I currently say:

> Usually not necessary due to path normalization (perhaps only necessary when parsing paths),
but may be used "for good measure" (user-friendly paths using the platform-specific delimiters).

What would you want it to say?

**Comment by wsor4035** [comment]
> > not depreciated/removed yet, see [minetest/minetest#13759](https://github.com/minetest/minetest/pull/13759) - maybe worth noting that its not needed, etc or something
> 
> I currently say:
> 
> > Usually not necessary due to path normalization (perhaps only necessary when parsing paths),
> > but may be used "for good measure" (user-friendly paths using the platform-specific delimiters).
> 
> What would you want it to say?

i was still semi thinking of depreciated, but its not, so this is fine

**Review by wsor4035 — APPROVED** [review]
good enough

**Pull request merged**
